apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  SERVICE_API_KEY: "tm_key_0bf9a6e3d17a8dc1a8e0524c00d710fdfe83f3f2d8e61f31e279fae327e97b78"
