apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:<SUBSTITUA_A_SENHA>@togglemaster-targeting-db.czkj64ocytsl.us-east-1.rds.amazonaws.com:5432/targeting_db?sslmode=require"
