apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:SuaSenhaForte2026!@togglemaster-flag-db.czkj64ocytsl.us-east-1.rds.amazonaws.com:5432/flags_db?sslmode=require"
