apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:SuaSenhaForte2026!@togglemaster-auth-db.czkj64ocytsl.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require"
  MASTER_KEY: "4e835ae3a5eccd2877b07df641d2e186d3d77cb5bb83d7bc328e9f737177e3a2"
